var networkMap = [
        {'displayShortname': 'eNB', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.enodeb'},
        {'displayShortname': 'SIAD', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.siad'},
        {'displayShortname': 'NodeB', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.nb'},
        {'displayShortname': 'eMSC', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.emsc'},
        {'displayShortname': 'RNC', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.rnc'},
        {'displayShortname': 'MGW', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.mgw'},
        {'displayShortname': 'SS7 GPORT', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.ss7_gport'},
        {'displayShortname': 'MSN', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.msn'},
        {'displayShortname': 'E-SMLC', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ran.e_smlc'},
        {'displayShortname': 'SGSN-S4', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.sgsn_s4'},
        {'displayShortname': 'MME', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.mme'},
        {'displayShortname': 'P_LRF (RDF)', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.p_lrf'},
        {'displayShortname': 'GMLC', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.gmlc'},
        {'displayShortname': 'PCEF', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.pcef'},
        {'displayShortname': 'SDG', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.sdg'},
        {'displayShortname': 'P-GW', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.p_gw'},
        {'displayShortname': 'S-GW', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.s_gw'},
        {'displayShortname': 'PAS', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.pas'},
        {'displayShortname': 'PCRF', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.pcrf'},
        {'displayShortname': 'MIND', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.mind'},
        {'displayShortname': 'APN DNS', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.apn_dns'},
        {'displayShortname': 'DRA EPC', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.dra_epc'},
        {'displayShortname': 'HSS EPC', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.hss_epc'},
        {'displayShortname': 'HLR', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.hlr'},
        {'displayShortname': 'CPM', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.cpm'},
        {'displayShortname': 'P-LRF/RDF', 'enclosingDomain': 'EPC', 'tosca_id': 'com.openecomp.trinity.epc.p_lrf_sup'},
        {'displayShortname': 'SBC', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.sbc'},
        {'displayShortname': 'ATGW', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.atgw'},
        {'displayShortname': 'IWF', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.iwf'},
        {'displayShortname': 'ATCF', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.atcf'},
        {'displayShortname': 'P-CSCF', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.p_cscf'},
        {'displayShortname': 'Transcoder', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.transcoder'},
        {'displayShortname': 'I-SBC', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.i_sbc'},
        {'displayShortname': 'SCC-AS', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.scc_as'},
        {'displayShortname': 'EATF', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.eatf'},
        {'displayShortname': 'TAS', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.tas_cts'},
        {'displayShortname': 'S-CSCF', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.s_cscf'},
        {'displayShortname': 'E-CSCF (911)', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.e_cscf'},
        {'displayShortname': 'I-CSCF', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.i_cscf'},
        {'displayShortname': 'TF / BGCF', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.tf_bgcf'},
        {'displayShortname': 'MGC-8', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.mgc8'},
        {'displayShortname': 'MRF', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.mrf'},
        {'displayShortname': 'USP DNS', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.dns'},
        {'displayShortname': 'DRA IMS', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.dra_ims'},
        {'displayShortname': 'ENUM', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.enum'},
        {'displayShortname': 'HSS IMS', 'enclosingDomain': 'USP', 'tosca_id': 'com.openecomp.trinity.usp.hss_ims'},
        {'displayShortname': 'CCF', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc1.ccf'},
        {'displayShortname': 'BGF', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc1.bgf'},
        {'displayShortname': 'vMS', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc1.ms'},
        {'displayShortname': 'vNS', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc1.ns'},
        {'displayShortname': 'vAS', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc1.as'},
        {'displayShortname': 'vA-SBG', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc1.a_sbg'},
        {'displayShortname': 'vDBE', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc1.dbe'},
        {'displayShortname': 'vN-SBG', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc1.n_sbg'},
        {'displayShortname': 'CCF', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc2.ccf'},
        {'displayShortname': 'BGF', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc2.bgf'},
        {'displayShortname': 'vMS', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc2.ms'},
        {'displayShortname': 'vNS', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc2.ns'},
        {'displayShortname': 'vAS', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc2.as'},
        {'displayShortname': 'vA-SBG', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc2.a_sbg'},
        {'displayShortname': 'vDBE', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc2.dbe'},
        {'displayShortname': 'vN-SBG', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.dc2.n_sbg'},
        {'displayShortname': 'PSX SIP', 'enclosingDomain': 'VNI', 'tosca_id': 'com.openecomp.trinity.vni.sip_psx'},
        {'displayShortname': 'PSX Policy', 'enclosingDomain': 'VNI', 'tosca_id': 'com.openecomp.trinity.vni.policy_psx'},
        {'displayShortname': 'IPBE', 'enclosingDomain': 'VNI', 'tosca_id': 'com.openecomp.trinity.vni.ipbe'},
        {'displayShortname': 'GSX', 'enclosingDomain': 'VNI', 'tosca_id': 'com.openecomp.trinity.vni.gsx'},
        {'displayShortname': 'BVoIP AS', 'enclosingDomain': 'VNI', 'tosca_id': 'com.openecomp.trinity.vni.bvoip_as'},
        {'displayShortname': 'NGBE', 'enclosingDomain': 'VNI', 'tosca_id': 'com.openecomp.trinity.vni.ngbe'},
        {'displayShortname': 'VoLTE UE', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ue'},
        {'displayShortname': '3G UE', 'enclosingDomain': 'RAN', 'tosca_id': 'com.openecomp.trinity.ue'},
        {'displayShortname': 'Trinity UE-A', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.ue'},
        {'displayShortname': 'Trinity UE-B', 'enclosingDomain': 'Datacenter', 'tosca_id': 'com.openecomp.trinity.ue'},
        {'displayShortname': 'VNI UE', 'enclosingDomain': 'VNI', 'tosca_id': 'com.openecomp.trinity.ue'},
        {'displayShortname': 'PSTN', 'enclosingDomain': 'VNI', 'tosca_id': 'com.openecomp.trinity.ue'}
    ];