/*-
 * ================================================================================
 * DCAE DMaaP Bus Controller Models
 * ================================================================================
 * Copyright (C) 2017 AT&T Intellectual Property
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ================================================================================
 */
package org.openecomp.dcae.dmaapbc.model;

/**
 * Bean that models a DMaaP Data Router publisher.
 */
public class DR_Pub extends DmaapObject {

	/** dcaeLocation tag where this publisher is deployed */
	private String dcaeLocationName;
	/** name used for basic authentication to DR */
	private String username;
	/** password used for basic authentication to DR */
	private String userpwd;
	/** tag of feed for which this publisher is a source */
	private String feedId;
	/** unique id of a DCAE publisher (generated by Data Router PROV) */
	private String pubId;

	public DR_Pub() {
	}

	public DR_Pub(Dmaap_Status status, String lastMod, String dcaeLocationName, String username, String userpwd,
			String feedId, String pubId) {
		super(lastMod, status);
		this.dcaeLocationName = dcaeLocationName;
		this.username = username;
		this.userpwd = userpwd;
		this.feedId = feedId;
		this.pubId = pubId;
	}

	public String getDcaeLocationName() {
		return dcaeLocationName;
	}

	public void setDcaeLocationName(String dcaeLocationName) {
		this.dcaeLocationName = dcaeLocationName;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpwd() {
		return userpwd;
	}

	public void setUserpwd(String userpwd) {
		this.userpwd = userpwd;
	}

	public String getFeedId() {
		return feedId;
	}

	public void setFeedId(String feedId) {
		this.feedId = feedId;
	}

	public String getPubId() {
		return pubId;
	}

	public void setPubId(String pubId) {
		this.pubId = pubId;
	}

	@Override
	public String toString() {
		return "DR_Pub[dcaeLocationName=" + dcaeLocationName + ", feedId=" + feedId + ", ...]";
	}

}
